### ISSUE TITLE
[EPIC] Docs and demos

### ISSUE THREAD

**Issue by chyuen-devsentient** [devsentient/devsentient.github.io#1]
- [ ] docs on how to start a nextjs app 
- [ ] commit code on creating a nextjs app in shakdemo
- [ ] update docs on adding a custom secret
- [ ] remove unused demos from shakdemo repo
- [ ] remove unused demos from sandbox repo
